# Generated by Django 5.2.13 on 2026-04-13 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "product_description",
                    models.TextField(
                        help_text="What are you selling? (e.g. spray-foam insulation services)"
                    ),
                ),
                (
                    "target_market",
                    models.TextField(
                        help_text="Who are you targeting? (e.g. GCs remodeling SFH in Bay Area)"
                    ),
                ),
                ("booking_link", models.URLField(blank=True, default="")),
                ("max_outreach_per_day", models.PositiveIntegerField(default=200)),
                ("max_outreach_per_week", models.PositiveIntegerField(default=1000)),
                ("model_blob", models.BinaryField(blank=True, null=True)),
                ("model_trained_at", models.DateTimeField(blank=True, null=True)),
                ("positive_labels", models.PositiveIntegerField(default=0)),
                ("negative_labels", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "llm_model",
                    models.CharField(default="claude-opus-4-6", max_length=128),
                ),
                (
                    "llm_base_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sendgrid_api_key",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "twilio_sid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "twilio_token",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("permits", "Building permits"),
                            ("solar", "Solar installations"),
                            ("rodents", "Rodent 311 reports"),
                            ("flood", "NOAA flood"),
                            ("construction", "Active construction"),
                            ("deconstruction", "Deconstruction / demo"),
                            ("realestate", "Real-estate sales"),
                            ("energy", "Energy benchmarking"),
                            ("places", "Google Places"),
                            ("yelp", "Yelp contractors"),
                            ("csv", "CSV import"),
                        ],
                        max_length=32,
                    ),
                ),
                ("interval_minutes", models.PositiveIntegerField(default=60)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="outreach.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=256)),
                ("title", models.CharField(max_length=512)),
                ("address", models.CharField(blank=True, default="", max_length=512)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                (
                    "project_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "project_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "contact_company",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "contact_source",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("qualification_score", models.FloatField(blank=True, null=True)),
                ("qualification_variance", models.FloatField(blank=True, null=True)),
                ("lead_score", models.PositiveIntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Discovered"),
                            ("QUALIFIED", "Qualified"),
                            ("READY_TO_CONTACT", "Ready to contact"),
                            ("CONTACTED", "Contacted"),
                            ("REPLIED", "Replied"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        default="DISCOVERED",
                        max_length=32,
                    ),
                ),
                (
                    "stage_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="outreach.campaign",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="outreach.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("discover", "Run discovery source"),
                            ("qualify", "Qualify discovered leads"),
                            ("outreach", "Send outreach for a lead"),
                            ("follow_up", "Follow up after N days"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="outreach.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="outreach.lead",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="outreach.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("qualified", "Qualified"),
                            ("telegram", "Telegram sent"),
                            ("email", "Email sent"),
                            ("whatsapp", "WhatsApp sent"),
                            ("reply", "Reply received"),
                            ("note", "Manual note"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="outreach.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="outreach.lead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign", "action", "-created_at"],
                        name="outreach_ac_campaig_ee6935_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["stage", "-qualification_score"],
                name="outreach_le_stage_99daa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["campaign", "stage"], name="outreach_le_campaig_0537a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lead",
            unique_together={("source", "external_id")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "scheduled_at"], name="outreach_ta_status_a9dfb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["type", "status"], name="outreach_ta_type_e3cf3b_idx"
            ),
        ),
    ]
