# Generated by Django 5.2.13 on 2026-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="llm_enricher_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="llm_qualifier_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="llm_writer_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="outreach_tone",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("friendly", "Friendly"),
                    ("urgent", "Urgent"),
                ],
                default="professional",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="enrichment_log",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="llm_outreach_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lead",
            name="llm_qualification_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("discover", "Run discovery source"),
                    ("enrich", "LLM contact enrichment"),
                    ("qualify", "Qualify discovered leads"),
                    ("outreach", "Send outreach for a lead"),
                    ("follow_up", "Follow up after N days"),
                ],
                max_length=32,
            ),
        ),
    ]
