# Generated by Django 5.2.13 on 2026-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0002_campaign_llm_enricher_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="lgbm_feature_importance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="campaign",
            name="lgbm_model_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="lgbm_trained_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
