# Generated by Django 5.2.13 on 2026-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0003_campaign_lgbm_feature_importance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="building_footprint_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lead",
            name="thermal_anomaly_k",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="kind",
            field=models.CharField(
                choices=[
                    ("permits", "Building permits"),
                    ("solar", "Solar installations"),
                    ("rodents", "Rodent 311 reports"),
                    ("flood", "NOAA flood"),
                    ("construction", "Active construction"),
                    ("deconstruction", "Deconstruction / demo"),
                    ("realestate", "Real-estate sales"),
                    ("energy", "Energy benchmarking"),
                    ("places", "Google Places"),
                    ("yelp", "Yelp contractors"),
                    ("thermal", "Thermal anomaly (Landsat)"),
                    ("csv", "CSV import"),
                ],
                max_length=32,
            ),
        ),
    ]
