# Generated by Django 5.2.13 on 2026-04-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0008_source_web_crawler_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('qualified', 'Qualified'), ('telegram', 'Telegram sent'), ('email', 'Email sent'), ('email_prospect', 'Personalized email sent to prospect'), ('whatsapp', 'WhatsApp sent'), ('reply', 'Reply received'), ('note', 'Manual note')], max_length=32),
        ),
    ]
